#!/bin/bash

# Configure python pip cache directory
export XDG_CACHE_HOME=/tmp/

# Activate python environment
source /usr/lib/ckan/env/bin/activate

# Install ckanext-govdatade and it's requirements
/usr/lib/ckan/env/bin/pip install --no-index -f /usr/lib/ckanext-govdatade/requirements ckanext-govdatade

# Create directory for reports
mkdir -p /var/lib/ckan/static/reports
chown -R ckan:ckan /var/lib/ckan

# Add ckan harvesters plugins to production.ini
if ! grep "ckan.plugins.*harvest ckan_harvester hamburg_harvester rlp_harvester berlin_harvester datahub_harvester rostock_harvester opennrw_harvester bremen_harvester gdi_harvester genesis_destatis_harvester destatis_harvester regionalstatistik_harvester sachsen_harvester bmbf_harvester bfj_harvester" /etc/ckan/default/production.ini
then
  sed -i '/^ckan.plugins/ s/$/ harvest ckan_harvester hamburg_harvester rlp_harvester berlin_harvester datahub_harvester rostock_harvester opennrw_harvester bremen_harvester gdi_harvester genesis_destatis_harvester destatis_harvester regionalstatistik_harvester sachsen_harvester bmbf_harvester bfj_harvester/' /etc/ckan/default/production.ini
fi
