#!/bin/bash

# Activate python environment
source /usr/lib/ckan/env/bin/activate

# Uninstall ckanext-searchindexhook
pip uninstall -y ckanext-govdatade

# Remove ckan harvesters plugins from production.ini
sed -i 's/ harvest ckan_harvester hamburg_harvester rlp_harvester berlin_harvester datahub_harvester rostock_harvester opennrw_harvester bremen_harvester gdi_harvester genesis_destatis_harvester destatis_harvester regionalstatistik_harvester sachsen_harvester bmbf_harvester bfj_harvester//' /etc/ckan/default/production.ini
